### ISSUE TITLE
Option to also plot samples

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/AbstractGPs.jl#119]
We currently have `plot`, which shows the marginals, and `sampleplot` which gives you samples.

It's commonly the case that I want both the marginals and samples when I'm plotting, so I would really like it if I could say
```julia
plot(f(x); samples=10)
```
to get a plot containing both the marginals and `10` samples. By default, `samples=0` would do nothing, so this would be non-breaking.

Is this something that others would like to have @devmotion @theogf @st-- , or am I on my own here?

**Comment by devmotion** [comment]
I imagine that others might want to plot both the marginals and samples as well (I am not working with GPs currently, so it does not really affect me) but I wonder if there is a clear advantage of the keyword argument version over the more modular
```julia
fx = f(x)
plot(fx)
sampleplot!(fx, 10)
```
It seems it is definitely easier to tune both parts of the plot independently if `plot` and `sampleplot!` are called separately - otherwise we would have to support special attributes for samples or somehow forward a dictionary of attributes for samples to the series of samples (which would be possible but feels a bit ugly...).

**Comment by willtebbutt** [comment]
Hmmmm on reflection I think you're probably correct. Will close. People should feel free to reopen if they feel strongly one way or the other.
