### ISSUE TITLE
`size` inconsistency

### ISSUE THREAD

**Issue by cscherrer** [JuliaGaussianProcesses/AbstractGPs.jl#136]
The [Soss tests](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/pr-62/test/compat/soss.jl) have this model:

```julia
k = SqExponentialKernel()
y = randn(3)
X = randn(3, 1)
x = [rand(1) for _ in 1:3]

gp_regression = Soss.@model X begin
    # Priors.
    α ~ LogNormal(0.0, 0.1)
    ρ ~ LogNormal(0.0, 1.0)
    σ² ~ LogNormal(0.0, 1.0)

    # Realized covariance function
    kernel = α * transform(SqExponentialKernel(), 1 / ρ)
    f = GP(kernel)

    # Sampling Distribution.
    y ~ f(X, σ²)
end
```

running this "by hand" gives
```julia
julia> k = SqExponentialKernel()
Squared Exponential Kernel

julia> y = randn(3)
3-element Vector{Float64}:
  0.4104263995264387
  1.4282768487843682
 -0.9190053618980447

julia> X = randn(3, 1)
3×1 Matrix{Float64}:
  0.8403190938843137
  0.8672163043894272
 -0.09545241492760646

julia> x = [rand(1) for _ in 1:3]
3-element Vector{Vector{Float64}}:
 [0.7607104031520515]
 [0.27095691264133337]
 [0.11087012586721845]

julia> α = rand(LogNormal(0.0, 0.1))
0.9566297929437682

julia> ρ = rand(LogNormal(0.0, 1.0))
5.9575826296063665

julia> σ² = rand(LogNormal(0.0, 1.0))
1.7373379697361795

julia> kernel = α * transform(SqExponentialKernel(), 1 / ρ)
Squared Exponential Kernel
        - Scale Transform (s = 0.16785331604642345)
        - σ² = 0.9566297929437682

julia> f = GP(kernel)
GP{ZeroMean{Float64}, ScaledKernel{TransformedKernel{SqExponentialKernel, ScaleTransform{Float64}}, Float64}}(ZeroMean{Float64}(), Squared Exponential Kernel
        - Scale Transform (s = 0.16785331604642345)
        - σ² = 0.9566297929437682)

julia> ydist = f(X, σ²)
FiniteGP{GP{ZeroMean{Float64}, ScaledKernel{TransformedKernel{SqExponentialKernel, ScaleTransform{Float64}}, Float64}}, ColVecs{Float64, Matrix{Float64}, SubArray{Float64, 1, Matrix{Float64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}}, Diagonal{Float64, Fill{Float64, 1, Tuple{Base.OneTo{Int64}}}}}(
f: GP{ZeroMean{Float64}, ScaledKernel{TransformedKernel{SqExponentialKernel, ScaleTransform{Float64}}, Float64}}(ZeroMean{Float64}(), Squared Exponential Kernel
        - Scale Transform (s = 0.16785331604642345)
        - σ² = 0.9566297929437682)
x: SubArray{Float64, 1, Matrix{Float64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}[[0.8403190938843137, 0.8672163043894272, -0.09545241492760646]]
Σy: [1.7373379697361795]
)
```

I'd expect this to be a distribution over R^3, corresponding to a `y` for each row of `X`. But
```julia
julia> size(ydist)
(1,)

julia> rand(ydist)
1-element Vector{Float64}:
 -1.6493519278768176
```

**Comment by willtebbutt** [comment]
Right, so `AbstractGPs` defaults to treating each column of a matrix as an observation, so that 3 x 1 matrix is treated as a single vector.

The (correct, although awfully documented) way to do this is to wrap your matrix in a `ColVecs` or a `RowVecs`. The former says "treat each column of this matrix as an input" is what happens by default (somewhere in `KernelFunctions` I believe), the latter says "treat each row of this matrix as an input".

`KernelFunctions` doesn't really believe in matrices per-se -- the fact that you can pass in a matrix is just some syntactic sugar at the top level that quickly wraps the matrix in a `ColVecs` or `RowVecs` (depending on some kwargs).

**Comment by cscherrer** [comment]
Thanks @willtebbutt . I guess this means the test needs some fixes?

**Comment by willtebbutt** [comment]
Yeah, I agree that it needs some fixes. My reading of the above code would be that the GP-bit of the code should be something like
```julia
f = GP(SEKernel())
x = randn(3)
y = randn(3)
```
where I've dispensed with the matrix, because it was representing 1-dimensional data anyway. So
```julia
f(x)
```
is a distribution over R^3, and
```julia
rand(f(x)) isa AbstractVector{<:Real}
length(rand(f(x))) == 3
```
Is this consistent with what you're after?

**Comment by cscherrer** [comment]
Works for me. @devmotion you updated the test recently, any thoughts on this?

**Comment by devmotion** [comment]
I'm sorry, I don't see any problem here, I don't think anything needs to be fixed. It seems you only have to wrap the matrix with `RowVecs` (which is done in the test already), as explained by @willtebbutt above. But maybe I miss something?

**Comment by cscherrer** [comment]
Ahh ok, I had missed that it's not the original `X` passed in to the model. Looks like that does the trick. Thanks @willtebbutt @devmotion
