### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/AbstractGPs.jl#5]
Stheno [has functionality to make plotting GPs in 1D easy](https://github.com/willtebbutt/Stheno.jl/blob/master/src/util/plotting.jl). It would be great if someone could port this over.

@sharanry this might be a good thing to do to make plotting stuff for the readme / examples easier :)

**Comment by sharanry** [comment]
Thanks for that! Used that to make this.

![anim](https://user-images.githubusercontent.com/19674071/81372748-bb8c5400-9118-11ea-8e38-e8baf030266c.gif)

**Comment by sharanry** [comment]
Slightly better looking with some samples.
![anim](https://user-images.githubusercontent.com/19674071/81373759-1cb52700-911b-11ea-9c38-41880ae88e62.gif)

**Comment by cpfiffer** [comment]
Is there anything cooler looking than a GP plot?

**Comment by sharanry** [comment]
> Is there anything cooler looking than a GP plot?

Hey! Do you have anything in mind?

**Comment by cpfiffer** [comment]
No, sadly. GP plots are the coolest so there can be no improvement.

**Comment by willtebbutt** [comment]
Closing this as I believe it to be resolved. Please re-open if there are improvements still to be made.

**Comment by nathanaelbosch** [comment]
>> Is there anything cooler looking than a GP plot?
>
> No, sadly. GP plots are the coolest so there can be no improvement.

I disagree! What about GP plots with animated samples?
![posterior2](https://user-images.githubusercontent.com/25008422/94360970-933dcb80-00a0-11eb-8fa7-54e41402c4c2.gif)

I made this gif last week, following [Philipp Hennig's Tech Report on "Animating Samples from Gaussian Distributions"](http://mlss.tuebingen.mpg.de/2013/2013/Hennig_2013_Animating_Samples_from_Gaussian_Distributions.pdf). The code to generate the sample paths is fairly generic, but making the actual animation did of course depend on Plots.jl.

I would love to make the code for these animations more accessible. Is this something you would like to include in AbstractGPs.jl? Or what would be the best approach?

**Comment by devmotion** [comment]
Very cool! A colleague of mine created the following webpage based on this idea: http://www.it.uu.se/edu/course/homepage/apml/GP/

I'm not sure if RecipesBase is sufficient for animations though, I've never written any recipes with animations. I don't think we would like to include any other plotting dependencies (e.g., on Plots) in AbstractGPs, maybe a separate package or just a gif with a link to the code might be more suitable in this case.

In general, I guess Makie might be even more suitable for animations than Plots. Have you ever played around with it? MakieRecipes doesn't support observables yet though, so also in this case it would not be possible to include just a recipe. It would still be cool to implement this with Makie (or rather AbstractPlotting to keep the backend choice up to the user).

**Comment by nathanaelbosch** [comment]
Thank you a lot for your reply! I also really like the GP visualization on the linked website.

As far as I know RecipesBase does not really extend to animations. Without adding new dependencies to AbstractGPs.jl, we could just add the function to compute a list of GP samples, each item corresponding to a frame, and a recipe to plot a single of these frames. But that does not seem very useful without the actual animation. So I think you are right that a separate package, or even just a documented repository, might be more useful for everybody.

I have never played around with Makie, but the many animated examples give me the first impression that it's more suitable for animations than Plots.jl. I will definitely try it out!

**Comment by devmotion** [comment]
I played around with Makie and created a repo with some recipes: https://github.com/devmotion/AbstractGPsMakie.jl

I tried to make everything reactive and included also a setting for the orbits of samples. It's quite easy to tune and record animations:
https://devmotion.github.io/AbstractGPsMakie.jl/dev/index.html

**Comment by theogf** [comment]
You missed a major opportunity to call your package MakieProcesses.jl!

**Comment by willtebbutt** [comment]
This is fantastic, particularly a fan of the animation.

I don't really know much about the relationship between recipes for Makie.jl and Plots.jl. Are they essentially two completely separate things? Looking at the code, they appear to be so.

What are your plans for this package @devmotion? I feel like we should at least be linking to it somewhere prominent in this package, preferably somewhere fairly obvious in the readme of this repo.

**Comment by devmotion** [comment]
There is/was MakieRecipes but it hasn't taken off, it seems, so the recipes in both ecosystems are different things. Also the recipe system and the theming in Makie is still not as mature and hasn't stabilized yet, it seems (e.g., it is not possible yet to use keyword arguments when converting input arguments: https://github.com/JuliaPlots/Makie.jl/issues/837). Another difference is that RecipesBase is a lightweight dependency whereas AbstractPlotting (the minimal interface without any Makie backends) has a huge number of dependencies.

I put together the package mainly since I switched from Plots to Makie more and more in my projects and wanted to learn a bit more about the recipe system and Makie internals. And I thought the animations could be fun 🎬 The Makie recipes provide a bit more functionality than the Plots recipes in AbstractGPs (I'm just a bit unsatisfied about how cumbersome it is to use custom themes - I wrote it such that it inherits user-specified defaults for bands, lines, etc but somehow Makie seems to ignore most of these user settings further up in the pipeline), so the package is in a usable state and could just benefit from more docs. IMO it should be transferred to the JuliaGaussianProcesses org and be mentioned somewhere in the documentation of AbstractGPs. Then users can start to submit bug reports, feature requests, and pull requests 🙂

**Comment by willtebbutt** [comment]
I am in favour of this. Looking forward to your PR to the AbstractGPs readme / docs :)

**Comment by devmotion** [comment]
I transferred the repo, I thought it's better to do it before registering it. I'll expand the docs and link it in AbstractGPs.

**Comment by devmotion** [comment]
I think this issue can be closed (again) since AbstractGPsMakie supports GP plots with animated samples.

BTW I extended the documentation a bit and added some tests in AbstractGPsMakie. I plan to register version 0.1 tomorrow.
