### ISSUE TITLE
FiniteGP not exported

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/AbstractGPs.jl#54]
Is it expected that FiniteGP is not always exported? It seems like a pretty important type to have outside of the module.

**Comment by sharanry** [comment]
Aren't finite GPs always created by giving data to an `AbstractGP`?
```julia

# Define GP prior with Matern32 kernel
f = GP(Matern32Kernel())

# Finite projection at the inputs `X`
fx = f(X,  0.001)
```
Why would you ever want to explicitly use `FiniteGP` constructor? I think we should dissuade the users from doing so.

**Comment by theogf** [comment]
I know, I know. But then why is AbstractGP also exported?
I also just got frustrated not having it in multiple situations (dispatching on it, looking for docs etc...)

**Comment by willtebbutt** [comment]
My approach to this has been only to export things that a user needs. Looking at our export list [here](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/617d21785436c59654819cebd48010ad57576343/src/AbstractGPs.jl#L14), I think this applies to everything on there _except_ `AbstractGP`, which a user shouldn't need to interact with.

I'm maybe going in the other direction, but I would be inclined to stop exporting `AbstractGP` in our next breaking release, rather than to start exporting other stuff.

**Comment by theogf** [comment]
Ok then we just need a PR to remove `AbstractGP` from the export list
